package com.sakethh.linkora.utils

enum class SysEnvKey {
    LINKORA_SERVER_USE_ENV_VAL, LINKORA_DATABASE_URL, LINKORA_DATABASE_USER, LINKORA_DATABASE_PASSWORD, LINKORA_SERVER_AUTH_TOKEN,
    LINKORA_HOST_ADDRESS, LINKORA_SERVER_PORT
}