package com.sakethh.linkora.domain.routes

enum class SavedAndFolderLinkRoute {
    CREATE_A_NEW_LINK, DELETE_A_LINK, UPDATE_LINKED_FOLDER_ID,
    UPDATE_TITLE_OF_THE_LINK, UPDATE_NOTE, DELETE_NOTE, UPDATE_USER_AGENT,
    GET_ALL_LINKS, GET_SAVED_LINKS, GET_LINKS_FROM_A_FOLDER
}