package com.sakethh.linkora.domain

sealed interface Route {
    enum class Link : Route {
        UPDATE_LINK_TITLE, UPDATE_LINK_NOTE, CREATE_A_NEW_LINK, DELETE_A_LINK, UPDATE_LINKED_FOLDER_ID, UPDATE_USER_AGENT, GET_LINKS_FROM_A_FOLDER, GET_LINKS, ARCHIVE_LINK, UNARCHIVE_LINK, MARK_AS_IMP, UNMARK_AS_IMP, UPDATE_LINK, DELETE_DUPLICATE_LINKS
    }

    enum class Folder : Route {
        CREATE_FOLDER, UPDATE_FOLDER, DELETE_FOLDER, GET_CHILD_FOLDERS, SEARCH_FOR_FOLDERS, GET_ROOT_FOLDERS, MARK_FOLDER_AS_ARCHIVE, MARK_AS_REGULAR_FOLDER, UPDATE_FOLDER_NAME, UPDATE_FOLDER_NOTE, DELETE_FOLDER_NOTE, MARK_FOLDERS_AS_ROOT
    }

    enum class Panel : Route {
        ADD_A_NEW_PANEL, ADD_A_NEW_FOLDER_IN_A_PANEL, DELETE_A_PANEL, UPDATE_A_PANEL_NAME, DELETE_A_FOLDER_FROM_ALL_PANELS, DELETE_A_FOLDER_FROM_A_PANEL, DELETE_ALL_FOLDERS_FROM_A_PANEL
    }

    enum class Sync : Route {
        TEST_BEARER, GET_UPDATES, GET_TOMBSTONES, DELETE_EVERYTHING, SERVER_IS_CONFIGURED
    }

    enum class MultiAction : Route {
        ARCHIVE_MULTIPLE_ITEMS, DELETE_MULTIPLE_ITEMS, MOVE_EXISTING_ITEMS, COPY_EXISTING_ITEMS, UNARCHIVE_MULTIPLE_ITEMS
    }

    enum class Tag : Route {
        CREATE_TAG, DELETE_TAG, RENAME_TAG, GET_TAGS
    }
}